[project]
name = "day5-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mayank Kumar", email = "mk4664348@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "pydantic>=2.13.5",
]

[project.scripts]
day5-api = "day5_api:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
